Repository livepoll/live-poll-api, pull requests merged in 2020-11, with the labels that each got.

#4 Add Swagger for API usage documentation
  pom.xml
  src/main/kotlin/de/livepoll/api/config/RoutingConfig.kt
  src/main/kotlin/de/livepoll/api/config/SwaggerConfig.kt
  src/main/resources/application.properties
Labels: documentation

#7 Feature login
  pom.xml
  src/main/kotlin/de/livepoll/api/LivePollApplication.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfiguration.kt
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/controller/UserController.kt
  src/main/kotlin/de/livepoll/api/entity/Answer.kt
  src/main/kotlin/de/livepoll/api/entity/OpenTextItem.kt
  src/main/kotlin/de/livepoll/api/entity/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/QuizItem.kt
  src/main/kotlin/de/livepoll/api/entity/User.kt
  src/main/kotlin/de/livepoll/api/entity/UserAttr.kt
  src/main/kotlin/de/livepoll/api/entity/db/Answer.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/OpenTextItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/User.kt
  src/main/kotlin/de/livepoll/api/entity/db/UserAttr.kt
  src/main/kotlin/de/livepoll/api/entity/dto/UserDto.kt
  src/main/kotlin/de/livepoll/api/repository/AnswerRepository.kt
  src/main/kotlin/de/livepoll/api/repository/MultipleChoiceItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/OpenTextItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/PollRepository.kt
  src/main/kotlin/de/livepoll/api/repository/QuizItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/UserAttrRepository.kt
  src/main/kotlin/de/livepoll/api/repository/UserRepository.kt
  src/main/kotlin/de/livepoll/api/service/UserService.kt
  src/main/resources/application.properties
  src/test/kotlin/de/livepoll/api/cucumber/CucumberIntegrationTest.kt
  src/test/kotlin/de/livepoll/api/cucumber/SpringIntegrationTest.kt
  src/test/kotlin/de/livepoll/api/cucumber/StepDefinitionIntegrationTest.kt
  src/test/resources/features/poll.feature
Labels: enhancement

#6 Add support for CodeCov
  README.md
  pom.xml
Labels: documentation

#11 Added json web token
  pom.xml
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/AuthenticationController.kt
  src/main/kotlin/de/livepoll/api/entity/db/User.kt
  src/main/kotlin/de/livepoll/api/entity/jwt/AuthenticationRequest.kt
  src/main/kotlin/de/livepoll/api/entity/jwt/AuthenticationResponse.kt
  src/main/kotlin/de/livepoll/api/repository/UserRepository.kt
  src/main/kotlin/de/livepoll/api/service/JwtUserDetailsService.kt
  src/main/kotlin/de/livepoll/api/util/JwtRequestFilter.kt
  src/main/kotlin/de/livepoll/api/util/JwtUtil.kt
Labels: enhancement

#12 SonarQube support
  .github/workflows/sonarqube-checks.yml
  README.md
Labels: documentation

#13 Add CORS policy configuration
  src/main/kotlin/de/livepoll/api/config/CorsConfig.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/AuthenticationController.kt
Labels: enhancement

#14 Registration
  src/main/kotlin/de/livepoll/api/config/MailConfig.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/UserController.kt
  src/main/kotlin/de/livepoll/api/entity/db/User.kt
  src/main/kotlin/de/livepoll/api/entity/db/VerificationToken.kt
  src/main/kotlin/de/livepoll/api/entity/dto/UserDto.kt
  src/main/kotlin/de/livepoll/api/exception/UserExistsException.kt
  src/main/kotlin/de/livepoll/api/repository/UserRepository.kt
  src/main/kotlin/de/livepoll/api/repository/VerificationTokenRepository.kt
  src/main/kotlin/de/livepoll/api/service/UserService.kt
  src/main/kotlin/de/livepoll/api/util/AccountListener.kt
  src/main/kotlin/de/livepoll/api/util/OnCreateAccountEvent.kt
Labels: enhancement

#17 Optimize code style & realize dsl queries
  src/main/kotlin/de/livepoll/api/config/MailConfig.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/config/SwaggerConfig.kt
  src/main/kotlin/de/livepoll/api/controller/AccountController.kt
  src/main/kotlin/de/livepoll/api/controller/AuthenticationController.kt
  src/main/kotlin/de/livepoll/api/controller/UserController.kt
  src/main/kotlin/de/livepoll/api/entity/db/Answer.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/OpenTextItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/UserAttr.kt
  src/main/kotlin/de/livepoll/api/entity/db/VerificationToken.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoOut.kt
  src/main/kotlin/de/livepoll/api/repository/UserRepository.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/JwtUserDetailsService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/service/UserService.kt
  src/main/kotlin/de/livepoll/api/util/AccountListener.kt
  src/main/kotlin/de/livepoll/api/util/JwtRequestFilter.kt
  src/main/kotlin/de/livepoll/api/util/JwtUtil.kt
  src/main/kotlin/de/livepoll/api/util/ModelMapper.kt
Labels: improvement

#19 Enhance JWT Security
  src/main/kotlin/de/livepoll/api/config/CorsConfig.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/AuthenticationController.kt
  src/main/kotlin/de/livepoll/api/controller/UserController.kt
  src/main/kotlin/de/livepoll/api/exception/EmailNotConfirmedException.kt
  src/main/kotlin/de/livepoll/api/repository/UserRepository.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/JwtUserDetailsService.kt
  src/main/kotlin/de/livepoll/api/util/JwtRequestFilter.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieCipher.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieUtil.kt
Labels: enhancement, improvement

#20 Cookie improvements
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/util/Constants.kt
  src/main/kotlin/de/livepoll/api/util/JwtUtil.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieCipher.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieUtil.kt
Labels: improvement

#25 Logout and improvements
  src/main/kotlin/de/livepoll/api/config/BlockedTokenConfig.kt
  src/main/kotlin/de/livepoll/api/config/CorsConfig.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/AuthenticationController.kt
  src/main/kotlin/de/livepoll/api/controller/UserController.kt
  src/main/kotlin/de/livepoll/api/entity/db/Answer.kt
  src/main/kotlin/de/livepoll/api/entity/db/BlockedToken.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/OpenTextItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/User.kt
  src/main/kotlin/de/livepoll/api/entity/db/UserAttr.kt
  src/main/kotlin/de/livepoll/api/entity/db/VerificationToken.kt
  src/main/kotlin/de/livepoll/api/repository/BlockedTokenRepository.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/JwtUserDetailsService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/util/JwtRequestFilter.kt
  src/main/kotlin/de/livepoll/api/util/JwtUtil.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieUtil.kt
  src/main/resources/application.properties
  src/main/resources/cert/localhost.crt
  src/main/resources/cert/localhost.key
  src/main/resources/cert/localhost.p12
Labels: enhancement, improvement

#27 Poll item implementation
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/controller/PollItemController.kt
  src/main/kotlin/de/livepoll/api/entity/db/Answer.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/OpenTextItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/db/PollItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItem.kt
  src/main/kotlin/de/livepoll/api/entity/dto/AnswerDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollItemDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemDtoOut.kt
  src/main/kotlin/de/livepoll/api/repository/AnswerRepository.kt
  src/main/kotlin/de/livepoll/api/repository/MultipleChoiceItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/OpenTextItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/PollItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/QuizItemRepository.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/util/ModelMapper.kt
Labels: enhancement
