Repository livepoll/live-poll-api, pull requests merged in 2021-06, with the labels that each got.

#104 Websocket improvements and documentation
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/controller/PollItemController.kt
  src/main/kotlin/de/livepoll/api/controller/WebSocketController.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/JwtUserDetailsService.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/service/WebSocketService.kt
  src/main/kotlin/de/livepoll/api/util/websocket/SubscribeListener.kt
Labels: documentation, improvement

#105 Change file library
  src/main/kotlin/de/livepoll/api/util/AccountListener.kt
Labels: improvement

#108 Update allowed CORS origins
  .github/scripts/docker-compose.yml
  .github/workflows/ci-with-docker-develop.yml
  .github/workflows/ci-with-docker.yml
  .github/workflows/ci.yml
  src/main/kotlin/de/livepoll/api/config/CorsConfig.kt
Labels: improvement

#109 Change volume file path relative to WSL2 (home)
  env/docker-compose.yml
Labels: improvement

#113 Workflow healthcheck fix
  .github/scripts/docker-compose.yml
  .github/workflows/ci.yml
Labels: bug

#110 Update poll scheduling
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/util/quartz/JobScheduleCrator.kt
  src/main/kotlin/de/livepoll/api/util/quartz/StartPollPresentationJob.kt
Labels: improvement

#114 Update quiz item answer order
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/main/kotlin/de/livepoll/api/util/CustomModelMapper.kt
  src/test/kotlin/de/livepoll/api/controller/v1/PollItemServiceTest.kt
Labels: bug, improvement

#115 Reformat code according to IntelliJ
  src/main/kotlin/de/livepoll/api/LivePollApplication.kt
  src/main/kotlin/de/livepoll/api/config/BlockedTokenConfig.kt
  src/main/kotlin/de/livepoll/api/config/QuartzSchedulerConfig.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/config/SwaggerConfig.kt
  src/main/kotlin/de/livepoll/api/config/WebSocketConfig.kt
  src/main/kotlin/de/livepoll/api/controller/WebSocketController.kt
  src/main/kotlin/de/livepoll/api/entity/db/BlockedToken.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItemAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/db/UserAttr.kt
  src/main/kotlin/de/livepoll/api/entity/db/VerificationToken.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemParticipantAnswerDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/OpenTextItemDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/OpenTextItemParticipantAnswerDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollItemDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemParticipantAnswerDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/UserDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/UserDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/jwt/AuthenticationRequest.kt
  src/main/kotlin/de/livepoll/api/entity/jwt/AuthenticationResponse.kt
  src/main/kotlin/de/livepoll/api/exception/EmailNotConfirmedException.kt
  src/main/kotlin/de/livepoll/api/exception/UserExistsException.kt
  src/main/kotlin/de/livepoll/api/repository/MultipleChoiceItemRepository.kt
  src/main/kotlin/de/livepoll/api/repository/UserAttrRepository.kt
  src/main/kotlin/de/livepoll/api/repository/UserRepository.kt
  src/main/kotlin/de/livepoll/api/repository/VerificationTokenRepository.kt
  src/main/kotlin/de/livepoll/api/util/JwtRequestFilter.kt
  src/main/kotlin/de/livepoll/api/util/JwtUtil.kt
  src/main/kotlin/de/livepoll/api/util/OnCreateAccountEvent.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieCipher.kt
  src/main/kotlin/de/livepoll/api/util/jwtCookie/CookieUtil.kt
  src/main/kotlin/de/livepoll/api/util/quartz/JobScheduleCrator.kt
  src/main/kotlin/de/livepoll/api/util/quartz/StopPollPresentationJob.kt
  src/main/kotlin/de/livepoll/api/util/websocket/CustomWebSocketHandshakeHandler.kt
  src/main/kotlin/de/livepoll/api/util/websocket/HttpHandshakeInterceptor.kt
  src/main/kotlin/de/livepoll/api/util/websocket/SubscribeListener.kt
  src/main/resources/quartz.properties
  src/test/kotlin/de/livepoll/api/cucumber/CucumberIntegrationTest.kt
  src/test/kotlin/de/livepoll/api/cucumber/stepdefinitions/PollStepDefinitions.kt
  src/test/kotlin/de/livepoll/api/cucumber/stepdefinitions/UserStepDefinitions.kt
  src/test/resources/quartz.properties
Labels: improvement

#116 Fix websocket issues
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/test/kotlin/de/livepoll/api/cucumber/stepdefinitions/UserStepDefinitions.kt
Labels: bug
