Repository livepoll/live-poll-api, pull requests merged in 2021-04, with the labels that each got.

#63 Updated poll endpoint
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoOut.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/util/CustomModelMapper.kt
  src/test/kotlin/de/livepoll/api/cucumber/stepdefinitions/PollStepDefinitions.kt
Labels: enhancement

#65 Adapt ER diagram to account for user answers
  media/er-diagram.drawio
  media/er-diagram.svg
Labels: documentation

#67 Development environment
  env/.gitignore
  env/README.md
  env/docker-compose.yml
  env/start.bat
  env/stop.bat
  env/volumes/mysql-data/.gitkeep
  env/volumes/mysql-logs/.gitkeep
  src/main/kotlin/de/livepoll/api/config/CorsConfig.kt
Labels: enhancement

#74 Websocket start
  pom.xml
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/config/WebSocketConfig.kt
  src/main/kotlin/de/livepoll/api/controller/WebSocketController.kt
  src/main/kotlin/de/livepoll/api/repository/PollRepository.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/service/WebSocketService.kt
  src/main/kotlin/de/livepoll/api/util/AccountListener.kt
Labels: bug, enhancement, improvement
