Repository livepoll/live-poll-api, pull requests merged in 2021-05, with the labels that each got.

#78 Websocket
  env/volumes/mysql-data/.gitkeep
  env/volumes/mysql-logs/.gitkeep
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/config/WebSocketConfig.kt
  src/main/kotlin/de/livepoll/api/controller/WebSocketController.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItemAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItemAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemParticipantAnswerDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/OpenTextItemParticipantAnswerDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoOut.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemParticipantAnswerDtoIn.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/JwtUserDetailsService.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/service/WebSocketService.kt
  src/main/kotlin/de/livepoll/api/util/CustomModelMapper.kt
  src/main/kotlin/de/livepoll/api/util/websocket/CustomWebSocketHandshakeHandler.kt
  src/main/kotlin/de/livepoll/api/util/websocket/HttpHandshakeInterceptor.kt
  src/main/kotlin/de/livepoll/api/util/websocket/SubscribeListener.kt
Labels: enhancement

#79 Testing/init junit5 tests
  src/main/kotlin/de/livepoll/api/entity/db/PollItem.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/test/kotlin/de/livepoll/api/LivePollApplicationTests.kt
  src/test/kotlin/de/livepoll/api/controller/v1/PollItemServiceTests.kt
  src/test/kotlin/de/livepoll/api/entity/PollTest.kt
Labels: test

#81 Implement suggestions from code inspection
  SECURITY.md
  env/README.md
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/WebSocketService.kt
  src/main/kotlin/de/livepoll/api/util/JwtUtil.kt
  src/main/kotlin/de/livepoll/api/util/websocket/CustomWebSocketHandshakeHandler.kt
  src/main/kotlin/de/livepoll/api/util/websocket/HttpHandshakeInterceptor.kt
  src/test/kotlin/de/livepoll/api/controller/v1/PollItemServiceTests.kt
  src/test/kotlin/de/livepoll/api/cucumber/RunCucumberTest.kt
  src/test/kotlin/de/livepoll/api/cucumber/stepdefinitions/PollStepDefinitions.kt
  src/test/kotlin/de/livepoll/api/cucumber/stepdefinitions/UserStepDefinitions.kt
Labels: improvement

#80 Feature/quiz item correct option
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/entity/dto/OpenTextItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
Labels: enhancement, improvement

#85 Add Newman to CI workflow
  .github/scripts/docker-compose.yml
  .github/workflows/ci.yml
  pom.xml
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/LivePollApplication.kt
  src/main/kotlin/de/livepoll/api/config/SecurityConfig.kt
  src/main/kotlin/de/livepoll/api/controller/AccountController.kt
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/controller/PollItemController.kt
  src/main/kotlin/de/livepoll/api/controller/WebSocketController.kt
  src/main/kotlin/de/livepoll/api/service/AccountService.kt
  src/main/kotlin/de/livepoll/api/service/WebSocketService.kt
  src/main/resources/application.yml
Labels: tests

#92 Presentation scheduling and design patterns
  media/answers_old.png
  media/answers_old.svg
  media/answers_with_inheritance.png
  media/answers_with_inheritance.svg
  pom.xml
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/config/QuartzSchedulerConfig.kt
  src/main/kotlin/de/livepoll/api/config/WebSocketConfig.kt
  src/main/kotlin/de/livepoll/api/controller/WebSocketController.kt
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItemAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/db/Poll.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItemAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/db/SelectionOptionAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollDtoOut.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
  src/main/kotlin/de/livepoll/api/service/WebSocketService.kt
  src/main/kotlin/de/livepoll/api/util/quartz/AutoWiringSpringBeanJobFactory.kt
  src/main/kotlin/de/livepoll/api/util/quartz/JobScheduleCrator.kt
  src/main/kotlin/de/livepoll/api/util/quartz/StartPollPresentationJob.kt
  src/main/kotlin/de/livepoll/api/util/quartz/StopPollPresentationJob.kt
  src/main/kotlin/de/livepoll/api/util/websocket/SubscribeListener.kt
  src/main/resources/application.yml
  src/main/resources/quartz.properties
  src/main/resources/quartz_tables.sql
  src/test/resources/application-test.yml
  src/test/resources/quartz.properties
  src/test/resources/quartz_tables.sql
Labels: enhancement

#94 Deploy code coverage to SonarQube
  .github/workflows/ci-with-docker-develop.yml
  .github/workflows/ci-with-docker.yml
  .github/workflows/ci.yml
  .github/workflows/docs-build.yml
  .github/workflows/sonarqube-checks.yml
Labels: improvement, tests

#93 Implement logic for coherently updating poll item positions
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/controller/PollItemController.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/OpenTextItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/PollItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/main/kotlin/de/livepoll/api/util/CustomModelMapper.kt
Labels: enhancement

#98 Show error messages locally and in GitHub tests
  .github/scripts/docker-compose.yml
  src/main/resources/application.yml
Labels: enhancement

#101 Bump Cucumber from 6.10.3 to 6.10.4
  .github/workflows/ci-with-docker-develop.yml
  .github/workflows/ci-with-docker.yml
  .github/workflows/ci.yml
  pom.xml
Labels: dependencies

#97 Fix/update poll item answer
  .github/scripts/docker-compose.yml
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/entity/db/MultipleChoiceItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/PollItemAnswerable.kt
  src/main/kotlin/de/livepoll/api/entity/db/QuizItem.kt
  src/main/kotlin/de/livepoll/api/entity/db/SelectionOptionAnswer.kt
  src/main/kotlin/de/livepoll/api/entity/dto/MultipleChoiceItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/entity/dto/QuizItemDtoIn.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
Labels: improvement

#102 Presentation improvements
  postman/Livepoll.postman_collection.json
  src/main/kotlin/de/livepoll/api/controller/PollController.kt
  src/main/kotlin/de/livepoll/api/service/PollItemService.kt
  src/main/kotlin/de/livepoll/api/service/PollService.kt
Labels: enhancement, improvement
